Disable URL signing for viahtml
hypothesis/h-vialib pull request #21
Opened 2021-02-26 15:07 UTC by marcospri

2021-02-26 16:37 UTC, seanh approved these changes

2021-03-03 17:26 UTC, seanh commented
Rebased

2021-03-03 17:41 UTC, seanh requested changes
On second look I'm not sure this works: I'm still seeing the `via.sec` param on the Via HTML URLs locally after changing LMS and Via 3 to use this.

I wonder if we should simplify this by changing Via 3 to accept requests if the `Referer` header points to either LMS or Via 3, the same as Via HTML does. Then we could simply remove the URL signing entirely from h-vialib's `url_for()` function

2021-03-03 18:06 UTC, seanh commented
Ah, I see what's happening: LMS does add `via.sec` when creating the Via _3_ URL. Even though signing is disabled when Via 3 creates the Via _HTML_, the original `via.sec` (the one for Via 3) gets passed through to Via HTML. It doesn't do any harm but it might be best to remove that to prevent confusion:

```diff
diff --git a/src/h_vialib/client.py b/src/h_vialib/client.py
index a6c1e4e..d628958 100644
--- a/src/h_vialib/client.py
+++ b/src/h_vialib/client.py
@@ -79,6 +79,9 @@ class ViaClient:  # pylint: disable=too-few-public-methods
         if blocked_for:
             query["via.blocked_for"] = blocked_for
 
+        if "via.sec" in query:
+            del query["via.sec"]
+
         if doc.is_html:
             # Optimisation to skip routing for documents we know are HTML
             via_url = self._url_for_html(doc.url, query)
```

Other than that, I think this does work correctly: Via 3 URLs are still being signed but Via HTML ones aren't

2021-03-04 10:03 UTC, seanh requested changes

2021-03-04 10:03 UTC, seanh commented on tests/unit/h_vialib/client_test.py
> +        url = "http://example.com/path?a=1&a=2&via.sec=REMOVED"
```suggestion
        url = "http://example.com/path?a=1&a=2&via.sec=THIS_SHOULD_BE_REMOVED"
```

2021-03-04 10:16 UTC, marcospri commented on tests/unit/h_vialib/client_test.py
> +        url = "http://example.com/path?a=1&a=2&via.sec=REMOVED"
Oh, much clearer yep :+1:

2021-03-04 11:59 UTC, merged